# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fb50320388b30c0e44675150794a3bc0d773b1bceb47a217e8658c4bca471917928adfdb8b117424acd643dae13cbfe590a6e67c24c4451982f43e7d3d04b06

test:
  secret_key_base: e5f996090f72fbbd9ddc824630a518516a62d2cf072cba6cf0475b921d371da605978be24e03ee11f8228146aa6c6c438ca8ff61b2ec2903e26f598b07e5efa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
